#!/bin/sh
. "$(dirname "$0")/_/husky.sh"



echo '🛠  🧪  Styling, testing and building you project before committing  🧪  🛠'

 #Check tsconfig standards

npm run check:types || 
(
    echo '❌ 😠 Failed Type Check 😠 ❌
        Make the changes required above!';
    false;

)

npm run check:format || 
(
    echo '😤 Your styling looks bad ! 😤
        Prettier check failed. Run npm run format, add changes and try commiting again';
    false;
)

npm run lint || 
(
    echo '🙎🏻‍♂️  Get this weak thing out of here! 🙎🏻‍♂️
            ESLint Check failed. Make the required changes mentioned above and try commiting again';
    false;
)
npx lint-staged

echo '🤩 ..Alright.. Code looks good to me.. You can type npm run build to build your code  ⚙️'